using Microsoft.AspNetCore.Mvc;
using ResturanrtManagement.Interface;
using ResturanrtManagement.Models;

namespace ResturanrtManagement.Controllers
{
    public class MenuController : Controller
    {
        // Inject the Service Layer Interface
        private readonly IMenuItemService _menuItemService;

        public MenuController(IMenuItemService menuItemService)
        {
            _menuItemService = menuItemService;
        }

        
        public async Task<IActionResult> Index()
        {
            // The service returns only the items marked as available (business logic)
            var menuItems = await _menuItemService.GetAvailableMenuItemsAsync();
            return View(menuItems);
        }

        // --- R: Read (Single) ---
        // GET: /Menu/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var item = await _menuItemService.GetMenuItemDetailsAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // --- C: Create ---
        // GET: /Menu/Create
        public IActionResult Create()
        {
            // Returns an empty view for creating a new MenuItem
            return View();
        }

        // POST: /Menu/Create
        [HttpPost]
        [ValidateAntiForgeryToken] // Security measure
        public async Task<IActionResult> Create([Bind("Name,Description,Price,Category,IsAvailable")] MenuItem item)
        {
            // Note: ItemId is generated by the database, so we only bind fields needed for creation.
            if (ModelState.IsValid)
            {
                await _menuItemService.CreateMenuItemAsync(item);
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // --- U: Update ---

        // GET: /Menu/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var item = await _menuItemService.GetMenuItemDetailsAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: /Menu/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,Name,Description,Price,Category,IsAvailable")] MenuItem item)
        {
            if (id != item.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Delegates the update and persistence logic to the service layer
                await _menuItemService.UpdateMenuItemAsync(item);
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // --- D: Delete ---

        // GET: /Menu/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var item = await _menuItemService.GetMenuItemDetailsAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: /Menu/DeleteConfirmed/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Delegates the delete logic to the service layer
            await _menuItemService.DeleteMenuItemAsync(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: /Menu/UpdatePrice/{id} (Existing action, kept for context)
        [HttpPost]
        public async Task<IActionResult> UpdatePrice(int id, [Bind("newPrice")] decimal newPrice)
        {
            // This specialized update action is often used for quick AJAX calls
            await _menuItemService.UpdatePriceAsync(id, newPrice);
            return RedirectToAction(nameof(Index));
        }
    }
}
